# A rule with no dependencies - make cannot see that the header changed
CFLAGS = -std=c23 -Wall -Wextra
demo: main.o greet.o
	$(CC) $(CFLAGS) -o $@ main.o greet.o
%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<
clean:
	rm -f demo *.o *.d
